import type { NextPage } from "next";
import loadConfig from "next/dist/server/config";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useQuery } from "react-query";
import InvoiceForm from "../components/InvoiceForm";
import Invoice from "../domain/invoice";
import generateInvoiceBuffer from "../faktura-react/generateInvoice";
import InvoiceVisual from "../faktura-react/InvoiceVisual/InvoiceVisual";
import styles from "../styles/Home.module.css";

const sampleInvoice: Invoice = {
  image: "https://quarnevalen.se/q20/start/arne.png",
  number: 1001,
  date: "2022-03-12",
  senderReference: "Sophie Dellmark",
  receiverReference: "QUapten Quaptensson",
  dueDate: "2022-04-12",
  Reciever: {
    name: "BobMcBob III",
    responsibleName: "Bob Bobson",
    responsibleAddress: "Arkdalerhögsgatan 139, 114 38, Skellefteå",
  },
  Sender: {
    name: "Quarnevalen",
    bankGiro: "8024-1156",
    address: "Drottning Kristinas Väg 15-19, 114 28, Stockholm",
    orgNr: "802411-2586",
    mail: "info@quarnevalen.se",
    phone: "070 1234 56 78",
    web: "squvalp.se",
  },
  products: [
    {
      name: "Squvalp deltagare",
      quantity: 28,
      price: 350,
    },
    {
      name: "Slutfestbiljett",
      quantity: 25,
      price: 400,
    },
    {
      name: "Solglasögon",
      quantity: 20,
      price: 20,
    },
  ],
};

const Home: NextPage = () => {
  const { status, data } = useQuery("invoices", async () => {
    const res = await fetch("/api/generatePdf", {
      method: "POST",
      body: JSON.stringify({ invoices: [sampleInvoice] }),
    });
    const data = await res.json();
    const pdf: string = data.pdfs[0].pdf;
    return pdf;
  });

  const pdfEncoding = `data:application/pdf;base64,${data}`;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <InvoiceForm />
        <div style={{ width: "60vw", height: "60vw" }}>
          {status === "loading" ? (
            <div>Loading...</div>
          ) : (
            <iframe src={pdfEncoding} height="100%" width="100%"></iframe>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
